name: punycode_converter
description: A robust Punycode converter that fully complies to RFC 3492 and RFC 5891.
version: 0.2.1
repository: https://github.com/darkxanter/punycode_converter

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
